# Script: generar_paginas_museo_tanques.ps1
# Genera los 6 HTML principales de museo-tanques

$dir = 'c:\Users\User\Desktop\DISEÑADOR GRAFICO\Plantillas\27) Google Antigravity\das museum 2\public\museo-tanques'

function Get-HTML ($title, $icon, $badge, $h1a, $h1b, $desc, $active) {
    $lines = New-Object System.Collections.Generic.List[string]

    $ci = if ($active -eq 'inicio') { 'text-primary' } else { 'text-gray-300 hover:text-primary' }
    $ct = if ($active -eq 'tour') { 'text-primary' } else { 'text-gray-300 hover:text-primary' }
    $cs = if ($active -eq 'servicios') { 'text-primary' } else { 'text-gray-300 hover:text-primary' }

    $lines.Add('<!DOCTYPE html>')
    $lines.Add('<html class="dark" lang="es">')
    $lines.Add('<head>')
    $lines.Add('    <meta charset="utf-8" />')
    $lines.Add('    <meta content="width=device-width, initial-scale=1.0" name="viewport" />')
    $lines.Add("    <title>$title &mdash; Museo de Tanques</title>")
    $lines.Add("    <meta name=`"description`" content=`"$desc`" />")
    $lines.Add('    <link href="https://fonts.googleapis.com" rel="preconnect" />')
    $lines.Add('    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect" />')
    $lines.Add('    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700;800;900&amp;family=Noto+Sans:wght@300;400;500;600;700&amp;family=Share+Tech+Mono&amp;display=swap" rel="stylesheet" />')
    $lines.Add('    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet" />')
    $lines.Add('    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"><\/script>')
    $lines.Add('    <script src="../js/config.js"><\/script>')
    $lines.Add('    <link href="../css/main.css" rel="stylesheet" />')
    $lines.Add('    <script defer="True" src="../js/i18n.js"><\/script>')
    $lines.Add('    <script defer="" src="../js/main.js"><\/script>')
    $lines.Add('    <style type="text/tailwindcss">')
    $lines.Add('        @layer components {')
    $lines.Add('            .topbar-global { @apply w-full bg-[#0a0f18]/95 backdrop-blur-md text-white py-3 z-[80] fixed top-0 left-0 right-0; }')
    $lines.Add('            .topbar-container { @apply max-w-[1400px] mx-auto px-6 flex justify-between items-center; }')
    $lines.Add('            .topbar-brand { @apply flex items-center gap-3 hover:opacity-80 transition-opacity; }')
    $lines.Add('            .topbar-logo { @apply h-8 w-auto invert brightness-200; }')
    $lines.Add('            .topbar-titles { @apply flex flex-col leading-none text-left; }')
    $lines.Add('            .topbar-subtitle { @apply font-serif italic text-[10px] text-gray-400 leading-tight; }')
    $lines.Add('            .topbar-title { @apply font-bold text-sm tracking-widest uppercase text-white; }')
    $lines.Add('            .topbar-utils { @apply flex items-center gap-4; }')
    $lines.Add('            .util-btn { @apply text-gray-400 hover:text-white transition-colors flex items-center justify-center; }')
    $lines.Add('            .util-divider { @apply w-px h-4 bg-gray-700 hidden md:block; }')
    $lines.Add('            .menu-parent { @apply flex items-center justify-between gap-4 text-gray-300 font-bold text-base capitalize tracking-wider cursor-pointer hover:text-primary transition-colors py-2 pr-12; }')
    $lines.Add('            .menu-parent .chevron { @apply text-xl transition-transform duration-300; }')
    $lines.Add('            .menu-parent.active .chevron { @apply rotate-180; }')
    $lines.Add('            .menu-divider { display: none; }')
    $lines.Add('            .menu-child { @apply flex items-center gap-3 text-gray-400 hover:text-primary transition-colors pl-8 border-l border-white/10 py-1.5 hover:border-primary ml-1; }')
    $lines.Add('            .menu-content { @apply grid grid-rows-[0fr] transition-[grid-template-rows] duration-300 overflow-hidden; }')
    $lines.Add('            .menu-content.open { @apply grid-rows-[1fr]; }')
    $lines.Add('            .menu-inner { @apply min-h-0 flex flex-col; }')
    $lines.Add('            @keyframes sun-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }')
    $lines.Add('            .theme-toggle .material-symbols-outlined { animation: sun-spin 10s linear infinite; display: inline-block; transform-origin: center; }')
    $lines.Add('        }')
    $lines.Add('    </style>')
    $lines.Add('</head>')
    $lines.Add('<body class="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 overflow-x-hidden">')
    $lines.Add('    <!-- OVERLAY -->')
    $lines.Add('    <div class="overlay fixed inset-0 bg-black/60 z-[90] backdrop-blur-sm hidden" id="left-overlay" onclick="toggleLeftMenu()"></div>')
    $lines.Add('')
    $lines.Add('    <!-- MENU IZQUIERDO (Museo de Tanques) -->')
    $lines.Add('    <aside class="fixed top-0 left-0 h-full w-80 bg-military-dark border-r border-white/10 z-[100] flex flex-col pt-10 transition-transform duration-400 -translate-x-full" id="left-sidebar">')
    $lines.Add('        <div class="px-8 pb-8 flex items-center justify-between border-b border-white/10">')
    $lines.Add('            <div class="flex flex-col">')
    $lines.Add('                <span class="text-xs font-black uppercase tracking-[0.2em] text-gray-400">Museo</span>')
    $lines.Add('                <span class="text-2xl font-black uppercase text-white tracking-tighter">Tanques</span>')
    $lines.Add('            </div>')
    $lines.Add('            <button class="text-gray-400 hover:text-white transition-colors" onclick="toggleLeftMenu()">')
    $lines.Add('                <span class="material-symbols-outlined text-3xl">close</span>')
    $lines.Add('            </button>')
    $lines.Add('        </div>')
    $lines.Add('        <nav class="flex-1 px-8 py-6 flex flex-col gap-2 overflow-y-auto">')
    $lines.Add("            <a class=`"group flex items-center gap-4 $ci transition-colors py-2`" href=`"index.html`">")
    $lines.Add('                <span class="material-symbols-outlined group-hover:scale-110 transition-transform">home</span>')
    $lines.Add('                <span class="font-bold text-base capitalize tracking-wider">Inicio</span>')
    $lines.Add('            </a>')
    $lines.Add("            <a class=`"group flex items-center gap-4 $ct transition-colors py-2`" href=`"tour.html`">")
    $lines.Add('                <span class="material-symbols-outlined group-hover:scale-110 transition-transform">360</span>')
    $lines.Add('                <span class="font-bold text-base capitalize tracking-wider">Tour Virtual</span>')
    $lines.Add('            </a>')
    $lines.Add('            <div>')
    $lines.Add('                <div class="menu-parent" onclick="toggleSubMenu(''museo-submenu'', this)">')
    $lines.Add('                    <div class="flex items-center gap-4">')
    $lines.Add('                        <span class="material-symbols-outlined">account_balance</span>')
    $lines.Add('                        <span class="font-bold text-base capitalize tracking-wider">Museo</span>')
    $lines.Add('                    </div>')
    $lines.Add('                    <span class="material-symbols-outlined chevron">expand_more</span>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="menu-content" id="museo-submenu">')
    $lines.Add('                    <div class="menu-inner">')
    $lines.Add('                        <a class="menu-child" href="nosotros.html"><span class="font-bold text-[13px] capitalize tracking-wider">Nosotros</span></a>')
    $lines.Add('                        <a class="menu-child" href="mision.html"><span class="font-bold text-[13px] capitalize tracking-wider">Mision y Vision</span></a>')
    $lines.Add('                        <a class="menu-child" href="video.html"><span class="font-bold text-[13px] capitalize tracking-wider">Video Institucional</span></a>')
    $lines.Add('                        <a class="menu-child" href="museum.html"><span class="font-bold text-[13px] capitalize tracking-wider">Historia</span></a>')
    $lines.Add('                        <a class="menu-child" href="mensaje.html"><span class="font-bold text-[13px] capitalize tracking-wider">Mensaje Comando</span></a>')
    $lines.Add('                        <a class="menu-child" href="noticias.html"><span class="font-bold text-[13px] capitalize tracking-wider">Noticias</span></a>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('            <div>')
    $lines.Add('                <div class="menu-parent" onclick="toggleSubMenu(''galeria-submenu'', this)">')
    $lines.Add('                    <div class="flex items-center gap-4">')
    $lines.Add('                        <span class="material-symbols-outlined">imagesmode</span>')
    $lines.Add('                        <span class="font-bold text-base capitalize tracking-wider">Galeria</span>')
    $lines.Add('                    </div>')
    $lines.Add('                    <span class="material-symbols-outlined chevron">expand_more</span>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="menu-content" id="galeria-submenu">')
    $lines.Add('                    <div class="menu-inner">')
    $lines.Add('                        <a class="menu-child" href="galeria.html"><span class="font-bold text-[13px] capitalize tracking-wider">Galeria</span></a>')
    $lines.Add('                        <a class="menu-child" href="fotos.html"><span class="font-bold text-[13px] capitalize tracking-wider">Fotos</span></a>')
    $lines.Add('                        <a class="menu-child" href="videos.html"><span class="font-bold text-[13px] capitalize tracking-wider">Videos</span></a>')
    $lines.Add('                        <a class="menu-child" href="audios.html"><span class="font-bold text-[13px] capitalize tracking-wider">Audios</span></a>')
    $lines.Add('                        <a class="menu-child" href="modelos3d.html"><span class="font-bold text-[13px] capitalize tracking-wider">Modelos 3D</span></a>')
    $lines.Add('                        <a class="menu-child" href="libros.html"><span class="font-bold text-[13px] capitalize tracking-wider">Libros</span></a>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('            <div>')
    $lines.Add('                <div class="menu-parent" onclick="toggleSubMenu(''contactos-submenu'', this)">')
    $lines.Add('                    <div class="flex items-center gap-4">')
    $lines.Add('                        <span class="material-symbols-outlined">contact_support</span>')
    $lines.Add('                        <span class="font-bold text-base capitalize tracking-wider">Contactos</span>')
    $lines.Add('                    </div>')
    $lines.Add('                    <span class="material-symbols-outlined chevron">expand_more</span>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="menu-content" id="contactos-submenu">')
    $lines.Add('                    <div class="menu-inner">')
    $lines.Add('                        <a class="menu-child" href="contactos.html"><span class="font-bold text-[13px] capitalize tracking-wider">Visitas</span></a>')
    $lines.Add('                        <a class="menu-child" href="sugerencias.html"><span class="font-bold text-[13px] capitalize tracking-wider">Sugerencias</span></a>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add("            <a class=`"group flex items-center gap-4 $cs transition-colors py-2 mt-2`" href=`"servicios.html`">")
    $lines.Add('                <span class="material-symbols-outlined group-hover:scale-110 transition-transform">construction</span>')
    $lines.Add('                <span class="font-bold text-base capitalize tracking-wider">Servicios</span>')
    $lines.Add('            </a>')
    $lines.Add('        </nav>')
    $lines.Add('        <div class="px-8 py-6 border-t border-white/10 mt-auto">')
    $lines.Add('            <a class="w-full block text-center bg-primary hover:bg-primary-hover text-white py-3 rounded font-black uppercase tracking-widest text-xs transition-colors" href="gallery.html">Entrar al Museo Principal</a>')
    $lines.Add('        </div>')
    $lines.Add('    </aside>')
    $lines.Add('')
    $lines.Add('    <div class="relative min-h-screen flex flex-col pt-[56px] md:pt-[60px] bg-military-dark">')
    $lines.Add('')
    $lines.Add('        <!-- TOPBAR -->')
    $lines.Add('        <div class="topbar-global topbar-main footer-fusion !fixed">')
    $lines.Add('            <div class="topbar-container relative z-10 w-full flex justify-between items-center px-6 h-[56px] md:h-[60px]">')
    $lines.Add('                <div class="flex items-center gap-4">')
    $lines.Add('                    <a class="topbar-brand" href="../index.html">')
    $lines.Add('                        <img alt="Logo" class="topbar-logo" src="../recursos/images/tapi-logo.svg" />')
    $lines.Add('                        <div class="topbar-titles">')
    $lines.Add('                            <span class="topbar-subtitle">Complejo</span>')
    $lines.Add('                            <span class="topbar-title">Museistico</span>')
    $lines.Add('                        </div>')
    $lines.Add('                    </a>')
    $lines.Add('                    <button class="text-gray-400 hover:text-white transition-colors flex items-center gap-2 ml-4 border-l border-white/10 pl-4" onclick="toggleLeftMenu()">')
    $lines.Add('                        <span class="material-symbols-outlined">menu</span>')
    $lines.Add('                        <span class="text-xs font-bold uppercase tracking-widest hidden md:inline">Museo de Tanques</span>')
    $lines.Add('                    </button>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="topbar-utils">')
    $lines.Add('                    <button aria-label="Buscar" class="util-btn" onclick="window.handleSearch &amp;&amp; window.handleSearch()"><span class="material-symbols-outlined">search</span></button>')
    $lines.Add('                    <div class="util-divider"></div>')
    $lines.Add('                    <button aria-label="Cambiar Idioma" class="util-btn" onclick="window.handleLang &amp;&amp; window.handleLang()"><span class="font-bold text-xs tracking-widest uppercase">ES</span></button>')
    $lines.Add('                    <div class="util-divider"></div>')
    $lines.Add('                    <button aria-label="Modo Dia/Noche" class="util-btn theme-toggle" onclick="window.toggleTheme &amp;&amp; window.toggleTheme()"><span class="material-symbols-outlined">light_mode</span></button>')
    $lines.Add('                    <div class="util-divider"></div>')
    $lines.Add('                    <a aria-label="Perfil" class="util-btn" href="../register.html"><span class="material-symbols-outlined">account_circle</span></a>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('            <div class="header-fusion-border"></div>')
    $lines.Add('        </div>')
    $lines.Add('')
    $lines.Add('        <!-- BREADCRUMB -->')
    $lines.Add('        <div class="max-w-[1400px] mx-auto px-6 pt-8 w-full">')
    $lines.Add('            <nav class="flex items-center gap-2 text-xs text-gray-500 uppercase tracking-widest">')
    $lines.Add('                <a href="../index.html" class="hover:text-primary transition-colors flex items-center gap-1">')
    $lines.Add('                    <span class="material-symbols-outlined text-sm">home</span> Complejo')
    $lines.Add('                </a>')
    $lines.Add('                <span class="material-symbols-outlined text-sm">chevron_right</span>')
    $lines.Add('                <a href="index.html" class="hover:text-primary transition-colors">Museo de Tanques</a>')
    $lines.Add('                <span class="material-symbols-outlined text-sm">chevron_right</span>')
    $lines.Add("                <span class=`"text-primary`">$title</span>")
    $lines.Add('            </nav>')
    $lines.Add('        </div>')
    $lines.Add('')
    $lines.Add('        <!-- CONTENIDO PRINCIPAL -->')
    $lines.Add('        <main class="flex-grow w-full max-w-[1400px] mx-auto px-6 py-12">')
    $lines.Add('            <!-- HERO -->')
    $lines.Add('            <section class="mb-16">')
    $lines.Add('                <div class="inline-flex items-center gap-2 bg-primary/20 border border-primary/40 text-primary text-xs font-bold px-4 py-1.5 rounded-full mb-6 uppercase tracking-widest">')
    $lines.Add("                    <span class=`"material-symbols-outlined text-sm`">$icon</span>")
    $lines.Add("                    $badge")
    $lines.Add('                </div>')
    $lines.Add("                <h1 class=`"text-5xl md:text-7xl font-black text-white uppercase leading-tight mb-6`">")
    $lines.Add("                    $h1a <br><span class=`"text-gray-400`">$h1b</span>")
    $lines.Add('                </h1>')
    $lines.Add('                <p class="text-gray-300 text-base md:text-lg max-w-3xl leading-relaxed border-l-4 border-primary pl-4">')
    $lines.Add("                    $desc")
    $lines.Add('                </p>')
    $lines.Add('            </section>')
    $lines.Add('')
    $lines.Add('            <!-- Aviso de borrador -->')
    $lines.Add('            <div class="w-full border border-yellow-500/30 bg-yellow-500/5 rounded-xl p-6 flex items-start gap-4 mb-12">')
    $lines.Add('                <span class="material-symbols-outlined text-yellow-400 text-2xl mt-0.5">edit_note</span>')
    $lines.Add('                <div>')
    $lines.Add('                    <p class="text-yellow-400 font-bold text-sm uppercase tracking-widest mb-1">Pagina en construccion &mdash; BORRADOR</p>')
    $lines.Add('                    <p class="text-gray-400 text-sm leading-relaxed">Esta pagina es un borrador. El contenido, imagenes y secciones seran editados con el material definitivo del Museo de Tanques.</p>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('')
    $lines.Add('            <!-- Bloques de contenido placeholder -->')
    $lines.Add('            <section class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">')
    $lines.Add('                <div class="bg-white/5 border border-white/10 rounded-xl p-8 flex flex-col gap-4">')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-2/3"></div>')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-full"></div>')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-5/6"></div>')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-3/4"></div>')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-full"></div>')
    $lines.Add('                    <div class="h-3 bg-white/10 rounded w-2/3"></div>')
    $lines.Add('                    <p class="text-gray-600 text-xs uppercase tracking-widest mt-4">[Bloque de texto 1 — editar con contenido real]</p>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="bg-white/5 border border-white/10 rounded-xl p-8 flex flex-col gap-4">')
    $lines.Add('                    <div class="h-48 bg-white/5 border border-white/10 rounded-lg flex items-center justify-center">')
    $lines.Add("                        <span class=`"material-symbols-outlined text-gray-600 text-5xl`">$icon</span>")
    $lines.Add('                    </div>')
    $lines.Add('                    <p class="text-gray-600 text-xs uppercase tracking-widest">[Imagen o media — editar con contenido real]</p>')
    $lines.Add('                </div>')
    $lines.Add('            </section>')
    $lines.Add('')
    $lines.Add('            <!-- Segundo bloque de placeholders -->')
    $lines.Add('            <section class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">')
    $lines.Add('                <div class="bg-white/5 border border-white/10 rounded-xl p-6 flex flex-col gap-3">')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-1/2"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-full"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-4/5"></div>')
    $lines.Add('                    <p class="text-gray-600 text-xs mt-2">[Tarjeta 1]</p>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="bg-white/5 border border-white/10 rounded-xl p-6 flex flex-col gap-3">')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-1/2"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-full"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-4/5"></div>')
    $lines.Add('                    <p class="text-gray-600 text-xs mt-2">[Tarjeta 2]</p>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="bg-white/5 border border-white/10 rounded-xl p-6 flex flex-col gap-3">')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-1/2"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-full"></div>')
    $lines.Add('                    <div class="h-2 bg-white/10 rounded w-4/5"></div>')
    $lines.Add('                    <p class="text-gray-600 text-xs mt-2">[Tarjeta 3]</p>')
    $lines.Add('                </div>')
    $lines.Add('            </section>')
    $lines.Add('')
    $lines.Add('            <!-- Navegacion rapida -->')
    $lines.Add('            <section class="border-t border-white/10 pt-12">')
    $lines.Add('                <p class="text-gray-500 text-xs uppercase tracking-widest mb-6">Otras secciones &mdash; Museo de Tanques</p>')
    $lines.Add('                <div class="flex flex-wrap gap-3">')
    $lines.Add('                    <a href="index.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">home</span> Inicio</a>')
    $lines.Add('                    <a href="tour.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">360</span> Tour Virtual</a>')
    $lines.Add('                    <a href="museum.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">account_balance</span> Museo</a>')
    $lines.Add('                    <a href="galeria.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">imagesmode</span> Galeria</a>')
    $lines.Add('                    <a href="contactos.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">contact_support</span> Contactos</a>')
    $lines.Add('                    <a href="servicios.html" class="border border-white/20 hover:border-primary text-gray-300 hover:text-primary px-4 py-2 rounded text-sm font-bold uppercase tracking-wider transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-sm">construction</span> Servicios</a>')
    $lines.Add('                </div>')
    $lines.Add('            </section>')
    $lines.Add('        </main>')
    $lines.Add('')
    $lines.Add('        <!-- FOOTER -->')
    $lines.Add('        <footer class="footer-fusion relative z-50 mt-auto pt-5">')
    $lines.Add('            <div class="footer-fusion-border"></div>')
    $lines.Add('            <div class="max-w-[1400px] mx-auto px-6 pb-10 pt-5">')
    $lines.Add('                <div class="grid grid-cols-1 md:grid-cols-12 gap-12 mb-20 text-left">')
    $lines.Add('                    <div class="col-span-1 md:col-span-4">')
    $lines.Add('                        <div class="flex items-center gap-3 text-white mb-6">')
    $lines.Add('                            <img alt="Museos TAPI Logo" class="h-12 w-auto invert" src="../recursos/images/tapi-logo.svg" />')
    $lines.Add('                            <div class="flex flex-col leading-none">')
    $lines.Add('                                <span class="font-serif italic text-xs text-accent-gold/80">Red de</span>')
    $lines.Add('                                <span class="font-black text-2xl tracking-tight uppercase bg-clip-text text-transparent bg-gradient-to-r from-primary via-white to-accent-gold">MUSEOS TAPI</span>')
    $lines.Add('                            </div>')
    $lines.Add('                        </div>')
    $lines.Add('                        <p class="text-gray-400 text-sm leading-relaxed mb-8">Guardamos la historia de los tanques y el legado de la caballeria. Una frontera donde el acero moderno se encuentra con el honor clasico.</p>')
    $lines.Add('                        <div class="flex flex-wrap gap-3 mt-6">')
    $lines.Add('                            <a aria-label="Facebook" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-blue-600 hover:text-white transition-all" href="#"><svg class="size-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path></svg></a>')
    $lines.Add('                            <a aria-label="Instagram" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-pink-600 hover:text-white transition-all" href="#"><svg class="size-4" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><rect height="20" rx="5" ry="5" width="20" x="2" y="2"></rect><path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path></svg></a>')
    $lines.Add('                            <a aria-label="X Twitter" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-white hover:text-black transition-all" href="#"><svg class="size-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg></a>')
    $lines.Add('                            <a aria-label="YouTube" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-red-600 hover:text-white transition-all" href="#"><svg class="size-5" fill="currentColor" viewBox="0 0 24 24"><path d="M21.582,6.186c-0.23-0.86-0.908-1.538-1.768-1.768C18.254,4,12,4,12,4S5.746,4,4.186,4.418c-0.86,0.23-1.538,0.908-1.768,1.768C2,7.746,2,12,2,12s0,4.254,0.418,5.814c0.23,0.86,0.908,1.538,1.768,1.768C5.746,20,12,20,12,20s6.254,0,7.814-0.418c0.861-0.23,1.538-0.908,1.768-1.768C22,16.254,22,12,22,12S22,7.746,21.582,6.186z"></path><path d="M10,15V9l5.2,3L10,15z"></path></svg></a>')
    $lines.Add('                            <a aria-label="Flickr" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-white hover:text-black transition-all group" href="#"><svg class="size-5" fill="none" viewBox="0 0 24 24"><circle class="fill-current group-hover:text-blue-500" cx="7" cy="12" r="4"></circle><circle class="fill-current group-hover:text-pink-500" cx="17" cy="12" r="4"></circle></svg></a>')
    $lines.Add('                            <a aria-label="TikTok" class="size-10 rounded-full bg-white/5 flex items-center justify-center text-gray-400 hover:bg-black hover:text-white transition-all" href="#"><svg class="size-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 2.23-1.15 4.39-2.92 5.67-1.85 1.34-4.3 1.69-6.44 1.02-2.31-.72-4.14-2.58-4.75-4.9-.5-1.92-.12-4.04 1.02-5.63 1.12-1.55 2.89-2.45 4.81-2.58 1.52-.1 3.03.18 4.41.81V15c-1.25-.63-2.73-.78-4.09-.43-1.4.37-2.6 1.4-3.15 2.72-.51 1.25-.42 2.73.23 3.91.66 1.19 1.88 1.99 3.23 2.1 1.39.12 2.82-.24 3.86-1.11 1.05-.88 1.66-2.2 1.68-3.59.02-4.8.01-9.61.02-14.41z"></path></svg></a>')
    $lines.Add('                        </div>')
    $lines.Add('                    </div>')
    $lines.Add('                    <div class="col-span-1 md:col-span-2">')
    $lines.Add('                        <h4 class="text-white text-xs font-bold uppercase tracking-widest mb-6 border-l-2 border-primary pl-3">Museo de Tanques</h4>')
    $lines.Add('                        <ul class="flex flex-col gap-3 text-gray-400 text-sm">')
    $lines.Add('                            <li><a class="hover:text-primary transition-colors" href="index.html">Inicio Tanques</a></li>')
    $lines.Add('                            <li><a class="hover:text-primary transition-colors" href="gallery.html">Galeria de Blindados</a></li>')
    $lines.Add('                            <li><a class="hover:text-primary transition-colors" href="events.html">Exhibiciones y Eventos</a></li>')
    $lines.Add('                            <li><a class="hover:text-primary transition-colors" href="preguntas.html">Preguntas Frecuentes</a></li>')
    $lines.Add('                            <li><a class="hover:text-primary transition-colors" href="donaciones.html">Apoyo y Donaciones</a></li>')
    $lines.Add('                        </ul>')
    $lines.Add('                    </div>')
    $lines.Add('                    <div class="col-span-1 md:col-span-2">')
    $lines.Add('                        <h4 class="text-white text-xs font-bold uppercase tracking-widest mb-6 border-l-2 border-accent-gold pl-3">Casa Historica</h4>')
    $lines.Add('                        <ul class="flex flex-col gap-3 text-gray-400 text-sm">')
    $lines.Add('                            <li><a class="hover:text-accent-gold transition-colors" href="../casa-historica/index.html">Inicio Casa</a></li>')
    $lines.Add('                            <li><a class="hover:text-accent-gold transition-colors" href="../casa-historica/about.html">Nuestra Historia</a></li>')
    $lines.Add('                            <li><a class="hover:text-accent-gold transition-colors" href="../casa-historica/gallery.html">Archivo Documental</a></li>')
    $lines.Add('                            <li><a class="hover:text-accent-gold transition-colors" href="../casa-historica/noticias.html">Boletin Oficial</a></li>')
    $lines.Add('                            <li><a class="hover:text-accent-gold transition-colors" href="../casa-historica/events.html">Exposiciones Epoca</a></li>')
    $lines.Add('                        </ul>')
    $lines.Add('                    </div>')
    $lines.Add('                    <div class="col-span-1 md:col-span-4">')
    $lines.Add('                        <h4 class="text-white text-xs font-bold uppercase tracking-widest mb-6 border-l-2 border-white/50 pl-3">Contacto Unico</h4>')
    $lines.Add('                        <ul class="flex flex-col gap-5 text-gray-400 text-sm">')
    $lines.Add('                            <li class="flex items-start gap-3"><span class="material-symbols-outlined text-white/50">location_on</span><span>Av. del Ejercito 1945,<br />Ciudad Capital, CP 28000</span></li>')
    $lines.Add('                            <li class="flex items-center gap-3"><span class="material-symbols-outlined text-white/50">call</span><span>+34 91 5555 4188</span></li>')
    $lines.Add('                            <li class="flex items-center gap-3"><span class="material-symbols-outlined text-white/50">mail</span><span class="hover:text-white cursor-pointer transition-colors">contacto@museodual.com</span></li>')
    $lines.Add('                        </ul>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('                <div class="border-t border-white/10 pt-8 flex flex-col md:flex-row justify-between items-center bg-white/5 p-6 rounded-xl backdrop-blur-sm">')
    $lines.Add('                    <div class="flex items-center gap-4 mb-4 md:mb-0">')
    $lines.Add('                        <div class="size-2 rounded-full bg-green-500 animate-pulse"></div>')
    $lines.Add('                        <span class="text-white font-bold text-xs uppercase tracking-widest">Estadisticas del Complejo</span>')
    $lines.Add('                    </div>')
    $lines.Add('                    <div class="flex flex-wrap justify-center gap-8 md:gap-12">')
    $lines.Add('                        <div class="text-center md:text-right"><span class="block text-[10px] text-gray-400 uppercase tracking-widest">Vehiculos y Armas</span><span class="block text-xl font-mono font-bold text-white">2,845</span></div>')
    $lines.Add('                        <div class="text-center md:text-right"><span class="block text-[10px] text-gray-400 uppercase tracking-widest">Piezas de Archivo</span><span class="block text-xl font-serif font-bold text-white">12,405</span></div>')
    $lines.Add('                        <div class="text-center md:text-right"><span class="block text-[10px] text-gray-400 uppercase tracking-widest">Visitantes</span><span class="block text-xl font-mono font-bold text-white">1,029,<span class="text-gray-400">482</span></span></div>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('            <div class="bg-black py-4 border-t border-white/5">')
    $lines.Add('                <div class="max-w-[1400px] mx-auto px-6 flex flex-col md:flex-row justify-between items-center text-[10px] text-gray-600 uppercase tracking-widest gap-4">')
    $lines.Add('                    <p>&copy; 2026 Museos TAPI. Todos los derechos reservados.</p>')
    $lines.Add('                    <div class="flex gap-6">')
    $lines.Add('                        <a class="hover:text-white transition-colors" href="#">Politica de Privacidad</a>')
    $lines.Add('                        <a class="hover:text-white transition-colors" href="#">Terminos de Uso</a>')
    $lines.Add('                    </div>')
    $lines.Add('                </div>')
    $lines.Add('            </div>')
    $lines.Add('        </footer>')
    $lines.Add('    </div>')
    $lines.Add('')
    $lines.Add('    <script>')
    $lines.Add('        function toggleLeftMenu() {')
    $lines.Add('            const sidebar = document.getElementById(''left-sidebar'');')
    $lines.Add('            const overlay = document.getElementById(''left-overlay'');')
    $lines.Add('            const isOpen = !sidebar.classList.contains(''-translate-x-full'');')
    $lines.Add('            if (isOpen) {')
    $lines.Add('                sidebar.classList.add(''-translate-x-full'');')
    $lines.Add('                overlay.classList.add(''hidden'');')
    $lines.Add('            } else {')
    $lines.Add('                sidebar.classList.remove(''-translate-x-full'');')
    $lines.Add('                overlay.classList.remove(''hidden'');')
    $lines.Add('            }')
    $lines.Add('        }')
    $lines.Add('        function toggleSubMenu(id, header) {')
    $lines.Add('            const content = document.getElementById(id);')
    $lines.Add('            if (!content) return;')
    $lines.Add('            const isOpen = content.classList.contains(''open'');')
    $lines.Add('            document.querySelectorAll(''.menu-content.open'').forEach(menu => {')
    $lines.Add('                if (menu.id !== id) {')
    $lines.Add('                    menu.classList.remove(''open'');')
    $lines.Add('                    const parent = menu.previousElementSibling;')
    $lines.Add('                    if (parent && parent.classList.contains(''menu-parent'')) parent.classList.remove(''active'');')
    $lines.Add('                }')
    $lines.Add('            });')
    $lines.Add('            if (isOpen) { content.classList.remove(''open''); header.classList.remove(''active''); }')
    $lines.Add('            else { content.classList.add(''open''); header.classList.add(''active''); }')
    $lines.Add('        }')
    $lines.Add('    <\/script>')
    $lines.Add('</body>')
    $lines.Add('</html>')

    return $lines -join "`r`n"
}

$pages = @(
    @{file = 'index.html'; title = 'Inicio'; icon = 'home'; active = 'inicio'; badge = 'Bienvenido al Museo'; h1a = 'Museo de'; h1b = 'Tanques'; desc = '[BORRADOR] Pagina de inicio del Museo de Tanques. Aqui ira la descripcion general, bienvenida y accesos rapidos a las secciones principales.' },
    @{file = 'tour.html'; title = 'Tour Virtual'; icon = '360'; active = 'tour'; badge = 'Experiencia Inmersiva'; h1a = 'Tour'; h1b = 'Virtual 360'; desc = '[BORRADOR] Recorre de forma inmersiva el museo con nuestro tour virtual 360 grados desde cualquier dispositivo.' },
    @{file = 'museum.html'; title = 'Museo'; icon = 'account_balance'; active = 'museo'; badge = 'Nuestra Identidad'; h1a = 'El'; h1b = 'Museo'; desc = '[BORRADOR] Historia, mision y vision del Museo de Tanques. Conoce el equipo y proyectos en curso.' },
    @{file = 'galeria.html'; title = 'Galeria'; icon = 'imagesmode'; active = 'galeria'; badge = 'Coleccion Multimedia'; h1a = 'Galeria de'; h1b = 'Blindados'; desc = '[BORRADOR] Explora fotografias, videos, audios y modelos 3D de nuestra coleccion de vehiculos blindados.' },
    @{file = 'contactos.html'; title = 'Contactos'; icon = 'contact_support'; active = 'contactos'; badge = 'Ponte en Contacto'; h1a = 'Contacta'; h1b = 'con Nosotros'; desc = '[BORRADOR] Informacion de contacto, visitas guiadas y sugerencias del publico.' },
    @{file = 'servicios.html'; title = 'Servicios'; icon = 'construction'; active = 'servicios'; badge = 'Para el Visitante'; h1a = 'Nuestros'; h1b = 'Servicios'; desc = '[BORRADOR] Servicios disponibles: cafeteria, guias especializados, tienda oficial, estacionamiento y mas.' }
)

foreach ($p in $pages) {
    $html = Get-HTML $p.title $p.icon $p.badge $p.h1a $p.h1b $p.desc $p.active
    $filePath = Join-Path $dir $p.file
    [System.IO.File]::WriteAllText($filePath, $html, [System.Text.Encoding]::UTF8)
    Write-Host "CREADO: $($p.file)" -ForegroundColor Green
}

Write-Host ''
Write-Host 'Todos los archivos generados correctamente.' -ForegroundColor Cyan
Get-ChildItem $dir -Filter '*.html' | Select-Object Name, LastWriteTime | Format-Table
